<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.nrg</groupId>
        <artifactId>test_dependencies</artifactId>
        <version>2.0.1</version>
    </parent>

    <artifactId>nrg_test</artifactId>
    <version>1.5-SNAPSHOT</version>

    <name>Base NRG Testing Framework</name>
    <description>Framework for testing of NRG applications.</description>

    <developers>
        <developer>
            <id>cmoore01</id>
            <name>Charlie Moore</name>
            <email>moore.c@wustl.edu</email>
        </developer>
    </developers>

    <scm>
        <connection>scm:git:https://bitbucket.org/xnatdev/nrg_test</connection>
        <url>scm:git:https://bitbucket.org/xnatdev/nrg_test</url>
    </scm>

    <properties>
        <test_utils.version>1.1</test_utils.version>
        <multiprocessor.version>3.0</multiprocessor.version>
        <test_listeners.version>4.1</test_listeners.version>
        <jira_reporter_version>1.1</jira_reporter_version>
        <grxnat.version>1.10-SNAPSHOT</grxnat.version>
    </properties>

    <build>
        <plugins>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

    <dependencies>

        <dependency>
            <groupId>org.nrg</groupId>
            <artifactId>test_utils</artifactId>
            <version>${test_utils.version}</version>
        </dependency>

        <dependency>
            <groupId>org.nrg</groupId>
            <artifactId>multiprocessor</artifactId>
            <version>${multiprocessor.version}</version>
        </dependency>

        <dependency>
            <groupId>org.nrg</groupId>
            <artifactId>test_listeners</artifactId>
            <version>${test_listeners.version}</version>
        </dependency>

        <dependency>
            <groupId>org.nrg</groupId>
            <artifactId>jira-reporter</artifactId>
            <version>${jira_reporter_version}</version>
        </dependency>

        <dependency>
            <groupId>org.nrg</groupId>
            <artifactId>grxnat</artifactId>
            <version>${grxnat.version}</version>
        </dependency>

        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
        </dependency>

        <dependency>
            <groupId>com.jayway.restassured</groupId>
            <artifactId>rest-assured</artifactId>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
        </dependency>

        <dependency>
            <groupId>org.hibernate</groupId>
            <artifactId>hibernate-core</artifactId>
        </dependency>

        <dependency>
            <groupId>net.lingala.zip4j</groupId>
            <artifactId>zip4j</artifactId>
        </dependency>

        <dependency>
            <groupId>commons-net</groupId>
            <artifactId>commons-net</artifactId>
        </dependency>

        <dependency>
            <groupId>org.reflections</groupId>
            <artifactId>reflections</artifactId>
        </dependency>

        <dependency>
            <groupId>com.hierynomus</groupId>
            <artifactId>sshj</artifactId>
        </dependency>

        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-math3</artifactId>
        </dependency>

        <dependency>
            <groupId>com.sun.mail</groupId>
            <artifactId>javax.mail</artifactId>
        </dependency>

        <dependency>
            <groupId>org.jsoup</groupId>
            <artifactId>jsoup</artifactId>
        </dependency>

        <dependency>
            <groupId>net.imagej</groupId>
            <artifactId>imagej</artifactId>
        </dependency>

        <dependency>
            <groupId>ome</groupId>
            <artifactId>bio-formats_plugins</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>ch.qos.logback</groupId>
                    <artifactId>logback-classic</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>ome</groupId>
            <artifactId>formats-gpl</artifactId>
        </dependency>

    </dependencies>

    <repositories>
        <repository>
            <id>org.nrg.xnat.maven.libraries.release</id>
            <name>XNAT Maven Release Libraries</name>
            <url>http://nrgxnat.jfrog.io/nrgxnat/libs-release</url>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
        <repository>
            <id>org.nrg.xnat.maven.libraries.snapshot</id>
            <name>XNAT Maven Snapshot Libraries</name>
            <url>http://nrgxnat.jfrog.io/nrgxnat/libs-snapshot</url>
            <releases>
                <enabled>false</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
                <updatePolicy>always</updatePolicy>
            </snapshots>
        </repository>
        <repository>
            <id>org.nrg.maven.artifacts.remote</id>
            <name>XNAT Remote Maven Repo</name>
            <url>http://nrgxnat.jfrog.io/nrgxnat/remote-repos</url>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>

</project>
